dataset:
  hospital:
    tuple_number_list: [ 10000, 20000, 30000, 40000, 50000 ]
    continuous_generate: False
  tax:
    tuple_number_list: [ 10000, 20000, 30000, 40000, 50000 ]
    continuous_generate: False
